
SELECT AGENCY_ID,
    VERSION,
    PID,
    AGENCY_CODE,
    AGENCY_NAME,
    ALH_ID,
    AGENCY_TYPE_CODE,
    AGENCY_TYPE_ID,
    ACCOUNT_ID,
    CREATED_ON,
    CREATED_BY_ID,
    UPDATED_ON,
    UPDATED_BY_ID FROM AGENCY;